version: '3.7'

services:
  jogosflamengo:
    build: .
    container_name: jogosflamengo
    expose:
      - "5000"
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy-jogosflamengo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

volumes:
  caddy_data:
  caddy_config:
